/*
 * This source file was generated by the Gradle 'init' task
 */
package WeekSwing;

import java.awt.BorderLayout;

import javax.swing.JFrame;
import javax.swing.JSplitPane;

public class App extends JFrame {
    public App() {
        setLayout(new BorderLayout());
        setTitle("Week Swing");
        setSize(920, 280);
        setResizable(true);

        JSplitPane splitPane = new JSplitPane();
        splitPane.setDividerLocation(240);
        splitPane.setDividerSize(4);
        splitPane.setLeftComponent(new SideBar());
        splitPane.setRightComponent(new Griddy());


        add(splitPane);
        add(new MenuItem("Welcome"), BorderLayout.NORTH);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(true);

    }

    public static void main(String[] args) {
        new App();
    }

}
